export const lightThemeVars = {
    '--k-theme-color': 'var(--k-color-gray-8) !important',
    '--k-theme-color-1': 'var(--k-color-gray-1) !important',
    '--k-theme-color-2': 'var(--k-color-gray-2) !important',
    '--k-theme-color-3': 'var(--k-color-gray-3) !important',
    '--k-theme-color-4': 'var(--k-color-gray-4) !important',
    '--k-theme-color-5': 'var(--k-color-gray-5) !important',
    '--k-theme-color-6': 'var(--k-color-gray-6) !important',
    '--k-theme-color-7': 'var(--k-color-gray-7) !important',
    '--k-theme-color-8': 'var(--k-color-gray-8) !important',
    '--k-theme-color-9': 'var(--k-color-gray-9) !important',

    '--k-theme-bgcolor': 'var(--k-color-gray-0) !important',
    '--k-theme-bgcolor-1': 'var(--k-color-gray-1) !important',
    '--k-theme-bgcolor-2': 'var(--k-color-gray-2) !important',
    '--k-theme-bgcolor-3': 'var(--k-color-gray-3) !important',
    '--k-theme-bgcolor-4': 'var(--k-color-gray-4) !important',
    '--k-theme-bgcolor-5': 'var(--k-color-gray-5) !important',
    '--k-theme-bgcolor-6': 'var(--k-color-gray-6) !important',
    '--k-theme-bgcolor-7': 'var(--k-color-gray-7) !important',
    '--k-theme-bgcolor-8': 'var(--k-color-gray-8) !important',
    '--k-theme-bgcolor-9': 'var(--k-color-gray-9) !important',
}
